### ISSUE TITLE
tink.http.HeaderField does not have a constructor only appears on Haxe v3.4.7

### ISSUE THREAD

**Issue by Talaween** [haxetink/tink_http#92] opened 2018-03-13 16:16 UTC
When updating to Haxe v3.4.7 the compilre gives this error:

tink.http.HeaderField does not have a constructor

everything works fine with Haxe v3.4.6

**Comment by kevinresol** [comment] 2018-03-20 15:21
I can't reproduce. I run the test suite with 3.4.7 and it is working fine.
Can you post some code?

**Comment by Talaween** [comment] 2018-03-22 14:52
If I upgrade to Haxe 3.4.7 the project fails to compile and gives me a long list of the same error happens whenver the HeaderField has been used in http library. as in this photo:
![image](https://user-images.githubusercontent.com/3596388/37777490-972477da-2ddf-11e8-9763-c0e2dbd86c8f.png)

also in my code when I try to use HeaderField also refuse to compile:
		_var field1:HeaderField = new HeaderField("Content-Type", "application/json");
		var fields = new Array<HeaderField>();
		fields.push(field1);_

with the same error.

also there is one more error I just have noticed:
                   _var router = new Router<Session, RootPath>(new RootPath());
it usually compiles successfully but with Haxe 3.4.7 it says
Server.hx:26: characters 15-60 : Unknown<0> cannot be constructed

I am using HaxeDevelop latest version, I tries this on two machies and the same scenario happens.

I have also updated all tink libraries from Haxelib except tink_web which I also use in this project however that one library the code on Github is the one that works while the one on Haxelib needs to be updated.

thank you very much for your response.

**Comment by kevinresol** [comment] 2018-03-22 14:56
Are you using the pure branches?

**Comment by Talaween** [comment] 2018-03-22 14:58
what do you mean pure branches?

I use tink libraries all up-to-date as in Haxelib except tink_web I use the one on Github

**Comment by kevinresol** [comment] 2018-03-22 15:09
Just pushed a fix, it is working fine on my machine now. Please have a try.

**Closed** 2018-03-22 15:08 UTC

**Comment by Talaween** [comment] 2018-03-22 15:13
yes it is working now, thank you very much for your help :)
